// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q      = new(Query)
	Admin  *admin
	Result *result
	Stats  *stats
	Survey *survey
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Admin = &Q.Admin
	Result = &Q.Result
	Stats = &Q.Stats
	Survey = &Q.Survey
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:     db,
		Admin:  newAdmin(db, opts...),
		Result: newResult(db, opts...),
		Stats:  newStats(db, opts...),
		Survey: newSurvey(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Admin  admin
	Result result
	Stats  stats
	Survey survey
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:     db,
		Admin:  q.Admin.clone(db),
		Result: q.Result.clone(db),
		Stats:  q.Stats.clone(db),
		Survey: q.Survey.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:     db,
		Admin:  q.Admin.replaceDB(db),
		Result: q.Result.replaceDB(db),
		Stats:  q.Stats.replaceDB(db),
		Survey: q.Survey.replaceDB(db),
	}
}

type queryCtx struct {
	Admin  IAdminDo
	Result IResultDo
	Stats  IStatsDo
	Survey ISurveyDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Admin:  q.Admin.WithContext(ctx),
		Result: q.Result.WithContext(ctx),
		Stats:  q.Stats.WithContext(ctx),
		Survey: q.Survey.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
