// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/dao/model"
)

func newStats(db *gorm.DB, opts ...gen.DOOption) stats {
	_stats := stats{}

	_stats.statsDo.UseDB(db, opts...)
	_stats.statsDo.UseModel(&model.Stats{})

	tableName := _stats.statsDo.TableName()
	_stats.ALL = field.NewAsterisk(tableName)
	_stats.ID = field.NewInt64(tableName, "id")
	_stats.SurveyID = field.NewInt64(tableName, "survey_id")
	_stats.QuestionID = field.NewString(tableName, "question_id")
	_stats.OptionID = field.NewString(tableName, "option_id")
	_stats.Count = field.NewInt32(tableName, "count")
	_stats.CreatedAt = field.NewTime(tableName, "created_at")
	_stats.UpdatedAt = field.NewTime(tableName, "updated_at")

	_stats.fillFieldMap()

	return _stats
}

// stats 统计表
type stats struct {
	statsDo statsDo

	ALL        field.Asterisk
	ID         field.Int64  // 自增ID
	SurveyID   field.Int64  // 问卷ID
	QuestionID field.String // 题目ID
	OptionID   field.String // 选项ID
	Count      field.Int32  // 数量
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (s stats) Table(newTableName string) *stats {
	s.statsDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stats) As(alias string) *stats {
	s.statsDo.DO = *(s.statsDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stats) updateTableName(table string) *stats {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.SurveyID = field.NewInt64(table, "survey_id")
	s.QuestionID = field.NewString(table, "question_id")
	s.OptionID = field.NewString(table, "option_id")
	s.Count = field.NewInt32(table, "count")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *stats) WithContext(ctx context.Context) IStatsDo { return s.statsDo.WithContext(ctx) }

func (s stats) TableName() string { return s.statsDo.TableName() }

func (s stats) Alias() string { return s.statsDo.Alias() }

func (s stats) Columns(cols ...field.Expr) gen.Columns { return s.statsDo.Columns(cols...) }

func (s *stats) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stats) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id"] = s.ID
	s.fieldMap["survey_id"] = s.SurveyID
	s.fieldMap["question_id"] = s.QuestionID
	s.fieldMap["option_id"] = s.OptionID
	s.fieldMap["count"] = s.Count
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s stats) clone(db *gorm.DB) stats {
	s.statsDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s stats) replaceDB(db *gorm.DB) stats {
	s.statsDo.ReplaceDB(db)
	return s
}

type statsDo struct{ gen.DO }

type IStatsDo interface {
	gen.SubQuery
	Debug() IStatsDo
	WithContext(ctx context.Context) IStatsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStatsDo
	WriteDB() IStatsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStatsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStatsDo
	Not(conds ...gen.Condition) IStatsDo
	Or(conds ...gen.Condition) IStatsDo
	Select(conds ...field.Expr) IStatsDo
	Where(conds ...gen.Condition) IStatsDo
	Order(conds ...field.Expr) IStatsDo
	Distinct(cols ...field.Expr) IStatsDo
	Omit(cols ...field.Expr) IStatsDo
	Join(table schema.Tabler, on ...field.Expr) IStatsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStatsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStatsDo
	Group(cols ...field.Expr) IStatsDo
	Having(conds ...gen.Condition) IStatsDo
	Limit(limit int) IStatsDo
	Offset(offset int) IStatsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStatsDo
	Unscoped() IStatsDo
	Create(values ...*model.Stats) error
	CreateInBatches(values []*model.Stats, batchSize int) error
	Save(values ...*model.Stats) error
	First() (*model.Stats, error)
	Take() (*model.Stats, error)
	Last() (*model.Stats, error)
	Find() ([]*model.Stats, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Stats, err error)
	FindInBatches(result *[]*model.Stats, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Stats) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStatsDo
	Assign(attrs ...field.AssignExpr) IStatsDo
	Joins(fields ...field.RelationField) IStatsDo
	Preload(fields ...field.RelationField) IStatsDo
	FirstOrInit() (*model.Stats, error)
	FirstOrCreate() (*model.Stats, error)
	FindByPage(offset int, limit int) (result []*model.Stats, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStatsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s statsDo) Debug() IStatsDo {
	return s.withDO(s.DO.Debug())
}

func (s statsDo) WithContext(ctx context.Context) IStatsDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s statsDo) ReadDB() IStatsDo {
	return s.Clauses(dbresolver.Read)
}

func (s statsDo) WriteDB() IStatsDo {
	return s.Clauses(dbresolver.Write)
}

func (s statsDo) Session(config *gorm.Session) IStatsDo {
	return s.withDO(s.DO.Session(config))
}

func (s statsDo) Clauses(conds ...clause.Expression) IStatsDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s statsDo) Returning(value interface{}, columns ...string) IStatsDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s statsDo) Not(conds ...gen.Condition) IStatsDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s statsDo) Or(conds ...gen.Condition) IStatsDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s statsDo) Select(conds ...field.Expr) IStatsDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s statsDo) Where(conds ...gen.Condition) IStatsDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s statsDo) Order(conds ...field.Expr) IStatsDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s statsDo) Distinct(cols ...field.Expr) IStatsDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s statsDo) Omit(cols ...field.Expr) IStatsDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s statsDo) Join(table schema.Tabler, on ...field.Expr) IStatsDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s statsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStatsDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s statsDo) RightJoin(table schema.Tabler, on ...field.Expr) IStatsDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s statsDo) Group(cols ...field.Expr) IStatsDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s statsDo) Having(conds ...gen.Condition) IStatsDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s statsDo) Limit(limit int) IStatsDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s statsDo) Offset(offset int) IStatsDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s statsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStatsDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s statsDo) Unscoped() IStatsDo {
	return s.withDO(s.DO.Unscoped())
}

func (s statsDo) Create(values ...*model.Stats) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s statsDo) CreateInBatches(values []*model.Stats, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s statsDo) Save(values ...*model.Stats) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s statsDo) First() (*model.Stats, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Stats), nil
	}
}

func (s statsDo) Take() (*model.Stats, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Stats), nil
	}
}

func (s statsDo) Last() (*model.Stats, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Stats), nil
	}
}

func (s statsDo) Find() ([]*model.Stats, error) {
	result, err := s.DO.Find()
	return result.([]*model.Stats), err
}

func (s statsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Stats, err error) {
	buf := make([]*model.Stats, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s statsDo) FindInBatches(result *[]*model.Stats, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s statsDo) Attrs(attrs ...field.AssignExpr) IStatsDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s statsDo) Assign(attrs ...field.AssignExpr) IStatsDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s statsDo) Joins(fields ...field.RelationField) IStatsDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s statsDo) Preload(fields ...field.RelationField) IStatsDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s statsDo) FirstOrInit() (*model.Stats, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Stats), nil
	}
}

func (s statsDo) FirstOrCreate() (*model.Stats, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Stats), nil
	}
}

func (s statsDo) FindByPage(offset int, limit int) (result []*model.Stats, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s statsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s statsDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s statsDo) Delete(models ...*model.Stats) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *statsDo) withDO(do gen.Dao) *statsDo {
	s.DO = *do.(*gen.DO)
	return s
}
