// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdmin = "admin"

// Admin 管理员表
type Admin struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                         // 自增ID
	Username  string    `gorm:"column:username;not null;comment:用户名" json:"username"`                                   // 用户名
	Password  string    `gorm:"column:password;not null;comment:密码" json:"password"`                                    // 密码
	Type      int8      `gorm:"column:type;not null;default:1;comment:类型 1-普通管理员 2-超级管理员" json:"type"`                  // 类型 1-普通管理员 2-超级管理员
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
