// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStats = "stats"

// Stats 统计表
type Stats struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                         // 自增ID
	SurveyID   int64     `gorm:"column:survey_id;not null;comment:问卷ID" json:"survey_id"`                                // 问卷ID
	QuestionID string    `gorm:"column:question_id;not null;comment:题目ID" json:"question_id"`                            // 题目ID
	OptionID   string    `gorm:"column:option_id;not null;comment:选项ID" json:"option_id"`                                // 选项ID
	Count      int32     `gorm:"column:count;not null;comment:数量" json:"count"`                                          // 数量
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Stats's table name
func (*Stats) TableName() string {
	return TableNameStats
}
