// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameSurvey = "survey"

// Survey 问卷表
type Survey struct {
	ID        int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                         // 自增ID
	AdminID   int64                 `gorm:"column:admin_id;not null;comment:所属管理员ID" json:"admin_id"`                               // 所属管理员ID
	Title     string                `gorm:"column:title;not null;comment:标题" json:"title"`                                          // 标题
	Type      int8                  `gorm:"column:type;not null;comment:类型 1-问卷 2-投票" json:"type"`                                  // 类型 1-问卷 2-投票
	Path      string                `gorm:"column:path;not null;comment:访问路径" json:"path"`                                          // 访问路径
	Schema    string                `gorm:"column:schema;not null;comment:结构" json:"schema"`                                        // 结构
	Status    int8                  `gorm:"column:status;not null;default:1;comment:状态 1-未发布 2-已发布" json:"status"`                  // 状态 1-未发布 2-已发布
	CreatedAt time.Time             `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3);comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time             `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3);comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt soft_delete.DeletedAt `gorm:"column:deleted_at;not null;comment:删除时间 (软删除);softDelete:milli" json:"-"`                // 删除时间 (软删除)
}

// TableName Survey's table name
func (*Survey) TableName() string {
	return TableNameSurvey
}
